# Generated by Django 2.0.6 on 2018-07-02 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZippedByType',
            fields=[
                ('zipped_by_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zipped_by_area', models.CharField(choices=[('state', 'state'), ('county', 'county'), ('quad', 'quad'), ('qquad', 'qquad'), ('natgrid', 'natgrid')], max_length=20, verbose_name='Zipped By Area')),
                ('zipped_by_area_name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Zipped By Type',
                'verbose_name_plural': 'Zipped By Types',
                'db_table': 'zipped_by_type',
            },
        ),
        migrations.AlterUniqueTogether(
            name='zippedbytype',
            unique_together={('zipped_by_area', 'zipped_by_area_name')},
        ),
    ]
