# Generated by Django 2.0.6 on 2018-08-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Filesize'),
        ),
    ]
