# Generated by Django 2.0.6 on 2018-07-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EpsgCode',
            new_name='EpsgRelate',
        ),
        migrations.RenameField(
            model_name='epsgrelate',
            old_name='epsg_code_id',
            new_name='epsg_relate_id',
        ),
        migrations.AlterModelTable(
            name='epsgrelate',
            table='epsg_relate',
        ),
    ]
