# Generated by Django 2.0.6 on 2018-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandrelate',
            options={'verbose_name': 'Band Lookup', 'verbose_name_plural': 'Band Lookups'},
        ),
        migrations.AlterModelOptions(
            name='categoryrelate',
            options={'verbose_name': 'Category Lookup', 'verbose_name_plural': 'Category Lookups'},
        ),
        migrations.AlterModelOptions(
            name='datatyperelate',
            options={'verbose_name': 'Data Type Lookup', 'verbose_name_plural': 'Data Type Lookups'},
        ),
        migrations.AlterModelOptions(
            name='epsgrelate',
            options={'verbose_name': 'EPSG Code Lookup', 'verbose_name_plural': 'EPSG Type Lookups'},
        ),
        migrations.AlterModelOptions(
            name='filetyperelate',
            options={'verbose_name': 'File Type Lookup', 'verbose_name_plural': 'File Type Lookups'},
        ),
        migrations.AlterModelOptions(
            name='resolutionrelate',
            options={'verbose_name': 'Resolution Lookup', 'verbose_name_plural': 'Resolution Lookups'},
        ),
        migrations.AlterModelOptions(
            name='userelate',
            options={'verbose_name': 'Use Lookup', 'verbose_name_plural': 'Use Lookups'},
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='source_abbreviation',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Source Abbreviation'),
        ),
    ]
