# Generated by Django 2.0.6 on 2018-07-02 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZippedByAreaType',
            fields=[
                ('zipped_by_area_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zipped_by_area_type', models.CharField(choices=[('state', 'state'), ('county', 'county'), ('quad', 'quad'), ('qquad', 'qquad'), ('natgrid', 'natgrid')], max_length=20, verbose_name='Zipped By Area Type')),
                ('zipped_by_area_type_name', models.CharField(max_length=50, unique=True, verbose_name='Zipped By Area Type Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Zipped By Area Type',
                'verbose_name_plural': 'Zipped By Area Types',
                'db_table': 'zipped_by_area_type',
            },
        ),
        migrations.DeleteModel(
            name='ZippedByType',
        ),
        migrations.AlterUniqueTogether(
            name='zippedbyareatype',
            unique_together={('zipped_by_area_type', 'zipped_by_area_type_name')},
        ),
    ]
