# Generated by Django 2.0.6 on 2018-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0002_auto_20180725_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetype',
            name='source_name',
            field=models.TextField(max_length=100, verbose_name='Source Name'),
        ),
    ]
