# Generated by Django 2.0.6 on 2018-07-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0002_auto_20180727_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='acquisition_date',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Acquisiiton Date'),
        ),
    ]
