# Generated by Django 2.0.6 on 2018-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0002_auto_20180702_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zippedbyareatype',
            name='zipped_by_area_type_name',
            field=models.CharField(max_length=50, verbose_name='Zipped By Area Type Name'),
        ),
    ]
