# Generated by Django 2.0.6 on 2018-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0003_auto_20180727_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='acquisition_date',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Acquisition Date'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'acquisition_date', 'source', 'authoritative', 'public', 'known_issues', 'md_filename', 'wms_link', 'popup_link', 'carto_map_id', 'overview_image', 'thumbnail_image', 'natural_image', 'urban_image', 'tile_index_url', 'supplemental_report_url', 'lidar_breaklines_url', 'coverage_extent', 'tags', 'license_type_id', 'agency_type_id', 'template_type_id')},
        ),
    ]
