# Generated by Django 2.0.6 on 2018-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0003_auto_20180702_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='zippedbyareatype',
            name='orig_data_download_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Original Data Download ID'),
        ),
    ]
