# Generated by Django 2.0.6 on 2018-07-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0003_auto_20180725_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='source_type_id',
            field=models.ForeignKey(blank=True, db_column='source_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_types', to='lcd.SourceType'),
        ),
    ]
