# Generated by Django 2.0.6 on 2018-08-16 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0003_auto_20180815_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resource_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Resource Type ID')),
                ('resource_type_name', models.TextField(max_length=50, unique=True, verbose_name='Resource Type Name')),
                ('resource_type_abbreviation', models.TextField(max_length=10, unique=True, verbose_name='Resource Type Abbreviation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
                'db_table': 'resource_type',
            },
        ),
        migrations.AddField(
            model_name='areatype',
            name='area_code',
            field=models.TextField(default=666, max_length=11, verbose_name='Area Code'),
            preserve_default=False,
        ),
    ]
