# Generated by Django 2.0.6 on 2018-07-03 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0004_zippedbyareatype_orig_data_download_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyType',
            fields=[
                ('county_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('county_fips', models.PositiveIntegerField(unique=True, verbose_name='County FIPS')),
                ('county_name', models.CharField(max_length=20, unique=True, verbose_name='County Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': 'county_type',
            },
        ),
        migrations.CreateModel(
            name='QQuadType',
            fields=[
                ('q_quad_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q_quad_id', models.PositiveSmallIntegerField(unique=True, verbose_name='QQuad ID')),
                ('q_quad_name', models.CharField(max_length=2, verbose_name='QQuad Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'qquad',
                'verbose_name_plural': 'qquads',
                'db_table': 'q_quad_type',
            },
        ),
        migrations.CreateModel(
            name='QuadType',
            fields=[
                ('quad_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usgs_doq_id', models.PositiveIntegerField(unique=True, verbose_name='USGS DOQ ID')),
                ('usgs_doq_name', models.CharField(max_length=40, verbose_name='USGS DOQ Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'quad',
                'verbose_name_plural': 'quads',
                'db_table': 'quad_type',
            },
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('state_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_fips', models.PositiveIntegerField(null=True, verbose_name='State FIPS')),
                ('state_name', models.CharField(max_length=25, verbose_name='State Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'state_type',
            },
        ),
        migrations.CreateModel(
            name='UsngType',
            fields=[
                ('usng_1000_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utm_grid_zone', models.CharField(max_length=4, verbose_name='UTM Grid Zone')),
                ('hk_meter_square', models.CharField(max_length=2, verbose_name='100000 Meter Square')),
                ('grid_coordinates', models.PositiveIntegerField(verbose_name='Grid Coordinates')),
                ('usng_name', models.CharField(max_length=16, verbose_name='USNG Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'us national grid',
                'verbose_name_plural': 'us national grids',
                'db_table': 'usng_1000_type',
            },
        ),
        migrations.AlterField(
            model_name='zippedbyareatype',
            name='zipped_by_area_type_name',
            field=models.CharField(max_length=50, verbose_name='Zipped By Area Name'),
        ),
        migrations.AlterUniqueTogether(
            name='usngtype',
            unique_together={('utm_grid_zone', 'hk_meter_square', 'grid_coordinates')},
        ),
        migrations.AlterUniqueTogether(
            name='statetype',
            unique_together={('state_fips', 'state_name')},
        ),
        migrations.AlterUniqueTogether(
            name='quadtype',
            unique_together={('usgs_doq_id', 'usgs_doq_name')},
        ),
        migrations.AlterUniqueTogether(
            name='qquadtype',
            unique_together={('q_quad_id', 'q_quad_name')},
        ),
        migrations.AlterUniqueTogether(
            name='countytype',
            unique_together={('county_fips', 'county_name')},
        ),
    ]
