# Generated by Django 2.0.6 on 2018-08-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0004_auto_20180816_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(db_column='resource_type_id', default='eb7741f9-e527-46e9-bb0e-a25de7babab0', on_delete=django.db.models.deletion.CASCADE, related_name='resource_types', to='lcd.ResourceType'),
        ),
    ]
