# Generated by Django 2.0.6 on 2018-07-03 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0005_auto_20180703_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('license_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_abbreviation', models.CharField(max_length=100, verbose_name='License Abbreviation')),
                ('license_name', models.CharField(max_length=200, verbose_name='License Name')),
                ('license_url', models.URLField(blank=True, null=True, verbose_name='License URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'license_type',
            },
        ),
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('template_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(max_length=100, unique=True, verbose_name='Template')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'template_type',
            },
        ),
        migrations.AlterModelOptions(
            name='qquadtype',
            options={'verbose_name': 'QQuad', 'verbose_name_plural': 'QQuads'},
        ),
        migrations.AlterModelOptions(
            name='quadtype',
            options={'verbose_name': 'Quad', 'verbose_name_plural': 'Quads'},
        ),
        migrations.AlterModelOptions(
            name='usngtype',
            options={'verbose_name': 'US National Grid', 'verbose_name_plural': 'US National Grids'},
        ),
        migrations.AlterUniqueTogether(
            name='licensetype',
            unique_together={('license_abbreviation', 'license_name', 'license_url')},
        ),
    ]
