# Generated by Django 2.0.6 on 2018-08-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0006_auto_20180817_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandrelate',
            name='band_type_id',
        ),
        migrations.RemoveField(
            model_name='bandrelate',
            name='collection_id',
        ),
        migrations.DeleteModel(
            name='BandType',
        ),
        migrations.AlterUniqueTogether(
            name='datatyperelate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='datatyperelate',
            name='collection_id',
        ),
        migrations.RemoveField(
            model_name='datatyperelate',
            name='data_type_id',
        ),
        migrations.DeleteModel(
            name='BandRelate',
        ),
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.DeleteModel(
            name='DataTypeRelate',
        ),
    ]
