# Generated by Django 2.0.6 on 2018-08-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0007_auto_20180817_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(db_column='resource_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='resource_types', to='lcd.ResourceType'),
        ),
    ]
