# Generated by Django 2.0.6 on 2018-08-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0009_auto_20180817_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatype',
            options={'ordering': ('area_type', 'area_type_name'), 'verbose_name': 'Area Type', 'verbose_name_plural': 'Area Types'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'ordering': ('resource_type_name',), 'verbose_name': 'Resource Type', 'verbose_name_plural': 'Resource Types'},
        ),
    ]
