# Generated by Django 2.0.6 on 2018-08-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0003_acdcview_ccrview'),
        ('lcd', '0010_auto_20180820_0818'),
    ]

    operations = [
    ]
