# Generated by Django 2.0.6 on 2018-08-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0011_merge_20180822_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'Dataset Collection', 'verbose_name_plural': 'Dataset Collections'},
        ),
    ]
