# Generated by Django 2.0.6 on 2018-09-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0012_auto_20180822_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemView',
            fields=[
                ('resource', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Resource URL')),
                ('filesize', models.PositiveIntegerField(blank=True, null=True, verbose_name='Filesize')),
                ('area_type_id', models.UUIDField(verbose_name='AreaType')),
                ('collection_id', models.UUIDField(verbose_name='Collection')),
                ('resource_type_id', models.UUIDField(verbose_name='ResourceType')),
                ('resource_type_name', models.TextField(max_length=50, verbose_name='Resource Type Name')),
                ('resource_type_abbreviation', models.TextField(max_length=10, verbose_name='Resource Type Abbreviation')),
            ],
            options={
                'verbose_name': 'Resource Management',
                'verbose_name_plural': 'Resource Managements',
                'db_table': 'resource_management',
                'managed': False,
            },
        ),
    ]
