# Generated by Django 2.0.6 on 2018-10-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0014_auto_20180927_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuaView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.UUIDField(verbose_name='Collection ID')),
                ('area_type', models.TextField(verbose_name='Area Type')),
            ],
            options={
                'verbose_name': 'Resource Unique Area',
                'verbose_name_plural': 'Resource Unique Areas',
                'db_table': 'resource_unique_areas',
                'managed': False,
            },
        ),
    ]
