# Generated by Django 2.0.6 on 2018-10-05 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0015_ruaview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccrview',
            options={'managed': False, 'verbose_name': 'Collection Catalog Record', 'verbose_name_plural': 'Cthumbollection Catalog Records'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Image ID'),
        ),
    ]
