# Generated by Django 2.0.6 on 2018-10-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0017_auto_20181005_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
    ]
