# Generated by Django 2.0.6 on 2018-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0020_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasView',
            fields=[
                ('area_type_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Area Type ID')),
                ('area_type_name', models.TextField(verbose_name='Area Type Name')),
                ('area_type', models.TextField(verbose_name='Area Type')),
                ('collections', models.TextField(verbose_name='Collections')),
            ],
            options={
                'verbose_name': 'Areas',
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
                'managed': False,
            },
        ),
    ]
