# Generated by Django 2.0.6 on 2018-10-17 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0021_areasview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Image ID'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'acquisition_date', 'source', 'authoritative', 'public', 'known_issues', 'md_filename', 'wms_link', 'popup_link', 'carto_map_id', 'thumbnail_image', 'tile_index_url', 'supplemental_report_url', 'lidar_breaklines_url', 'coverage_extent', 'tags', 'license_type_id', 'agency_type_id', 'template_type_id')},
        ),
    ]
