# Generated by Django 2.0.6 on 2018-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0023_auto_20181017_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='filesize',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Filesize'),
        ),
    ]
