# Generated by Django 2.0.6 on 2018-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0025_auto_20181109_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetype',
            name='filter_name',
            field=models.TextField(default='Order Only', max_length=50, verbose_name='Filter Name'),
            preserve_default=False,
        ),
    ]
