# Generated by Django 2.0.8 on 2018-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0026_templatetype_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='filter_name',
            field=models.TextField(default='test', max_length=50, verbose_name='Filter Name'),
            preserve_default=False,
        ),
    ]
