# Generated by Django 2.0.8 on 2018-12-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0029_outsideentityservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='template_type_id',
            field=models.ForeignKey(db_column='template_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='template_types', to='lcd.TemplateType'),
        ),
    ]
