# Generated by Django 2.0.8 on 2019-01-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0030_auto_20181210_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areatype',
            unique_together={('area_type', 'area_code')},
        ),
    ]
