# Generated by Django 2.0.8 on 2019-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0031_auto_20190129_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='partners',
            field=models.TextField(blank=True, null=True, verbose_name='Partners'),
        ),
    ]
