# Generated by Django 2.0.8 on 2019-02-01 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0032_collection_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('source_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Source Type ID')),
                ('source_name', models.TextField(max_length=100, verbose_name='Source Name')),
                ('source_abbreviation', models.TextField(blank=True, max_length=100, null=True, verbose_name='Source Abbreviation')),
                ('source_website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Source Website')),
                ('source_contact', models.TextField(blank=True, max_length=255, null=True, verbose_name='Source Contact')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Source Type',
                'verbose_name_plural': 'Source Types',
                'db_table': 'source_type',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sourcetype',
            unique_together={('source_name', 'source_abbreviation', 'source_website', 'source_contact')},
        ),
        migrations.AddField(
            model_name='collection',
            name='source_type_id',
            field=models.ForeignKey(blank=True, db_column='source_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_types', to='lcd.SourceType'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'acquisition_date', 'source', 'authoritative', 'public', 'known_issues', 'md_filename', 'wms_link', 'popup_link', 'carto_map_id', 'thumbnail_image', 'tile_index_url', 'supplemental_report_url', 'lidar_breaklines_url', 'coverage_extent', 'tags', 'license_type_id', 'agency_type_id', 'source_type_id', 'template_type_id')},
        ),
    ]
