# Generated by Django 2.0.8 on 2019-02-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0033_auto_20190201_0845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'acquisition_date', 'authoritative', 'public', 'known_issues', 'md_filename', 'wms_link', 'popup_link', 'carto_map_id', 'thumbnail_image', 'tile_index_url', 'supplemental_report_url', 'lidar_breaklines_url', 'coverage_extent', 'tags', 'license_type_id', 'source_type_id', 'template_type_id')},
        ),
    ]
