# Generated by Django 2.0.8 on 2019-02-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0034_auto_20190204_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='agency_type_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='source',
        ),
    ]
