# Generated by Django 2.0.8 on 2019-02-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0035_auto_20190204_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyType',
        ),
    ]
