# Generated by Django 2.0.8 on 2019-02-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0037_sourcetype_source_data_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image Caption'),
        ),
    ]
