# Generated by Django 2.2 on 2019-04-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0038_image_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcdcView',
        ),
        migrations.DeleteModel(
            name='RuaView',
        ),
    ]
