# Generated by Django 2.0.13 on 2019-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0039_auto_20190403_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='XlargeSupplemental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'X-Large Supplemental',
                'verbose_name_plural': 'X-Large Supplementals',
            },
        ),
    ]
