# Generated by Django 2.0.13 on 2019-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0042_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='publication_date',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Publication Date'),
        ),
    ]
