# Generated by Django 2.0.13 on 2019-11-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0043_collection_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccrview',
            options={'managed': False, 'verbose_name': 'Collection Catalog Record', 'verbose_name_plural': 'Collection Catalog Records'},
        ),
    ]
