# Generated by Django 2.0.13 on 2020-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0044_auto_20191121_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='thumbnail_image',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Thumb Image'),
        ),
    ]
