# Generated by Django 3.0.8 on 2021-03-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0045_auto_20200429_1417'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ccrview',
            table='collection_catalog_geom_record',
        ),
    ]
