# Generated by Django 3.0.8 on 2021-04-07 21:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0046_auto_20210315_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCollectionMetaView',
            fields=[
                ('collection_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Collection ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('acquisition_date', models.TextField(verbose_name='Acquisition Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('public', models.BooleanField(verbose_name='Public')),
                ('thumbnail_image', models.TextField(verbose_name='Thumb Image')),
                ('tile_index_url', models.URLField(verbose_name='Tile Index URL')),
                ('category', models.TextField(verbose_name='Category')),
                ('file_type', models.TextField(verbose_name='File Type')),
                ('source_name', models.TextField(verbose_name='Source Name')),
                ('source_abbreviation', models.TextField(verbose_name='Source Abbreviation')),
                ('source_contact', models.TextField(verbose_name='Source Contact')),
                ('license_name', models.TextField(verbose_name='License Name')),
                ('license_abbreviation', models.TextField(verbose_name='License Abbreviation')),
                ('license_url', models.CharField(max_length=255, verbose_name='License URL')),
                ('template', models.TextField(verbose_name='Template')),
                ('availability', models.TextField(verbose_name='Availability')),
                ('counties', models.TextField(verbose_name='Counties')),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Coverage Geometry')),
            ],
            options={
                'verbose_name': 'Catalog Collection Metadatum',
                'verbose_name_plural': 'Catalog Collection Metadata',
                'db_table': 'catalog_collection_meta',
                'managed': False,
            },
        ),
    ]
