# Generated by Django 3.0.8 on 2021-04-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0047_catalogcollectionmetaview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ccrview',
            table='collection_catalog_record',
        ),
    ]
