# Generated by Django 3.2.5 on 2021-08-09 19:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0048_auto_20210415_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFootprint',
            fields=[
                ('footprint_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Footprint ID')),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcd.collection')),
            ],
            options={
                'verbose_name': 'Collection Footprint',
                'verbose_name_plural': 'Collection Footprints',
            },
        ),
    ]
