# Generated by Django 3.2.5 on 2021-08-10 14:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0049_collectionfootprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfootprint',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcd.collection', verbose_name='Collection ID'),
        ),
        migrations.AlterField(
            model_name='collectionfootprint',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='The Geometry'),
        ),
    ]
