# Generated by Django 3.2.5 on 2021-08-10 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0050_auto_20210810_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfootprint',
            name='footprint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Footprint ID'),
        ),
        migrations.AlterField(
            model_name='collectionfootprint',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='The Geometry'),
        ),
    ]
