# Generated by Django 3.2.5 on 2021-08-10 18:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0051_auto_20210810_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfootprint',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='The Geometry'),
        ),
    ]
