# Generated by Django 3.2.5 on 2021-08-11 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0054_alter_collectionfootprint_the_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfootprint',
            name='collection_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lcd.collection', verbose_name='Collection ID'),
        ),
        migrations.AlterField(
            model_name='collectionfootprint',
            name='footprint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Footprint ID'),
        ),
        migrations.AlterModelTable(
            name='collectionfootprint',
            table='collection_footprint',
        ),
    ]
