# Generated by Django 3.2.14 on 2022-12-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0056_auto_20220819_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='s_three_link',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='S3 Link'),
        ),
    ]
