# Generated by Django 3.2.14 on 2022-12-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0057_collection_s_three_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='s_three_link',
            new_name='s_three_location',
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'acquisition_date', 'authoritative', 'public', 'known_issues', 'md_filename', 'wms_link', 'popup_link', 'carto_map_id', 'thumbnail_image', 'tile_index_url', 'supplemental_report_url', 'lidar_breaklines_url', 'lidar_buildings_url', 'coverage_extent', 'tags', 'license_type_id', 'source_type_id', 'template_type_id', 's_three_location')},
        ),
    ]
