# Generated by Django 3.2.14 on 2022-12-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0058_auto_20221209_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='s_three_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Link'),
        ),
    ]
