# Generated by Django 3.2.14 on 2022-12-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0059_alter_collection_s_three_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='s_three_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Key'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'acquisition_date', 'authoritative', 'public', 'known_issues', 'md_filename', 'wms_link', 'popup_link', 'carto_map_id', 'thumbnail_image', 'tile_index_url', 'supplemental_report_url', 'lidar_breaklines_url', 'lidar_buildings_url', 'coverage_extent', 'tags', 'license_type_id', 'source_type_id', 'template_type_id', 's_three_key')},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='s_three_location',
        ),
    ]
