# Generated by Django 3.2.19 on 2023-05-31 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0060_auto_20221209_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Resource Type Id')),
                ('setting_name', models.TextField(max_length=32, verbose_name='Setting Name')),
                ('setting_value', models.TextField(max_length=32, verbose_name='Setting Value')),
            ],
            options={
                'verbose_name': 'Captains Log',
                'verbose_name_plural': 'Captains Logs',
                'db_table': 'captains_log',
            },
        ),
    ]
