# Generated by Django 3.2.19 on 2023-05-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0061_loggertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggertype',
            name='setting_name',
            field=models.CharField(max_length=32, verbose_name='Setting Name'),
        ),
        migrations.AlterField(
            model_name='loggertype',
            name='setting_value',
            field=models.CharField(max_length=32, verbose_name='Setting Value'),
        ),
    ]
