# Generated by Django 3.2.19 on 2023-06-30 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0062_auto_20230531_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFoods',
            fields=[
                ('favorite_food_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Favorite Food Id')),
                ('food', models.CharField(max_length=80, verbose_name='Food')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Favorite Food',
                'verbose_name_plural': 'Favorite Foods',
                'db_table': 'favorite_foods',
            },
        ),
    ]
