# Generated by Django 4.2.9 on 2024-07-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcd', '0062_auto_20230531_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='resource_type_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lcd.resourcetypecategory'),
        ),
    ]
