# Generated by Django 2.0.13 on 2019-07-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0002_auto_20190710_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TnrisDocUrl',
            new_name='TnrisDocument',
        ),
        migrations.RenameModel(
            old_name='TnrisImageUrl',
            new_name='TnrisImage',
        ),
        migrations.AlterModelOptions(
            name='tnrisdocument',
            options={'verbose_name': 'Tnris Document', 'verbose_name_plural': 'Tnris Documents'},
        ),
        migrations.AlterModelOptions(
            name='tnrisimage',
            options={'verbose_name': 'Tnris Image', 'verbose_name_plural': 'Tnris Images'},
        ),
        migrations.RenameField(
            model_name='tnrisdocument',
            old_name='doc_id',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='tnrisdocument',
            old_name='doc_name',
            new_name='document_name',
        ),
        migrations.RenameField(
            model_name='tnrisdocument',
            old_name='doc_url',
            new_name='document_url',
        ),
        migrations.AlterModelTable(
            name='tnrisdocument',
            table='tnris_document',
        ),
        migrations.AlterModelTable(
            name='tnrisimage',
            table='tnris_image',
        ),
    ]
