# Generated by Django 2.0.13 on 2019-07-16 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0003_auto_20190711_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnrisForumTraining',
            fields=[
                ('training_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Training ID')),
                ('training_day', models.PositiveSmallIntegerField(verbose_name='Forum Training Day')),
                ('title', models.CharField(max_length=255, verbose_name='Training Title')),
                ('start_date_time', models.DateTimeField(verbose_name='Training Start Date & Time')),
                ('end_date_time', models.DateTimeField(verbose_name='Training End Date & Time')),
                ('instructor', models.CharField(max_length=100, verbose_name='Training Instructor')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Training Cost')),
                ('registration_open', models.BooleanField(default=False, verbose_name='Registration Open')),
                ('location', models.CharField(max_length=255, verbose_name='Training Location')),
                ('room', models.CharField(max_length=255, verbose_name='Training Room')),
                ('max_students', models.PositiveSmallIntegerField(verbose_name='Max Student Amount')),
                ('instructor_bio', models.TextField(verbose_name='Training Instructor Bio')),
                ('description', models.TextField(verbose_name='Training Description')),
                ('teaser', models.TextField(verbose_name='Training Teaser')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Tnris Forum Training',
                'verbose_name_plural': 'Tnris Forum Trainings',
                'db_table': 'tnris_forum_training',
            },
        ),
        migrations.CreateModel(
            name='TnrisTraining',
            fields=[
                ('training_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Training ID')),
                ('start_date_time', models.DateTimeField(verbose_name='Training Start Date & Time')),
                ('end_date_time', models.DateTimeField(verbose_name='Training End Date & Time')),
                ('title', models.CharField(max_length=255, verbose_name='Training Title')),
                ('instructor', models.CharField(max_length=100, verbose_name='Training Instructor')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Training Cost')),
                ('registration_open', models.BooleanField(default=False, verbose_name='Registration Open')),
                ('instructor_bio', models.TextField(verbose_name='Training Instructor Bio')),
                ('description', models.TextField(verbose_name='Training Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Tnris Training',
                'verbose_name_plural': 'Tnris Trainings',
                'db_table': 'tnris_training',
            },
        ),
    ]
