# Generated by Django 2.0.13 on 2019-07-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0004_tnrisforumtraining_tnristraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrisforumtraining',
            name='instructor_bio',
            field=models.TextField(blank=True, verbose_name='Training Instructor Bio'),
        ),
    ]
