# Generated by Django 2.0.13 on 2019-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0005_auto_20190716_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnristraining',
            name='instructor_bio',
            field=models.TextField(blank=True, verbose_name='Training Instructor Bio'),
        ),
    ]
