# Generated by Django 2.0.13 on 2019-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0007_auto_20190716_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrisforumtraining',
            name='room',
            field=models.CharField(blank=True, max_length=255, verbose_name='Training Room'),
        ),
    ]
