# Generated by Django 2.0.13 on 2019-07-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0008_auto_20190717_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrisforumtraining',
            name='max_students',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Max Student Amount'),
        ),
    ]
