# Generated by Django 2.0.13 on 2019-08-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0009_auto_20190717_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnristraining',
            name='instructor_bio',
        ),
    ]
