# Generated by Django 2.0.13 on 2019-08-07 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0010_remove_tnristraining_instructor_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnrisInstructor',
            fields=[
                ('instructor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Instructor ID')),
                ('name', models.CharField(max_length=100, verbose_name='Instructor Name')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Instructor Company')),
                ('bio', models.TextField(blank=True, verbose_name='Instructor Bio')),
                ('headshot', models.URLField(blank=True, max_length=255, verbose_name='Image URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Tnris Instructor',
                'verbose_name_plural': 'Tnris Instructors',
                'db_table': 'tnris_instructor',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tnrisforumtraining',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='tnrisforumtraining',
            name='instructor_bio',
        ),
        migrations.AddField(
            model_name='tnrisforumtraining',
            name='training_instructor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnris_org.TnrisInstructor'),
        ),
    ]
