# Generated by Django 2.0.13 on 2019-08-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0011_auto_20190807_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnrisforumtraining',
            old_name='training_instructor_id',
            new_name='training_instructor',
        ),
    ]
