# Generated by Django 2.0.13 on 2019-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0012_auto_20190807_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrisinstructor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instructor Company'),
        ),
    ]
