# Generated by Django 2.0.13 on 2019-08-08 15:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0014_auto_20190807_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnrisInstructorRelate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Relate Primary Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('instructor_relate_id', models.ForeignKey(db_column='instructor_relate_id', on_delete=django.db.models.deletion.CASCADE, related_name='tnrs_instructor_ids', to='tnris_org.TnrisInstructor')),
            ],
            options={
                'verbose_name': 'Tnris Instructor Relate',
                'verbose_name_plural': 'Tnris Instructor Relates',
                'db_table': 'tnris_instructor_relate',
            },
        ),
        migrations.RemoveField(
            model_name='tnrisforumtraining',
            name='training_instructor',
        ),
        migrations.AddField(
            model_name='tnrisinstructorrelate',
            name='training_relate_id',
            field=models.ForeignKey(db_column='training_relate_id', on_delete=django.db.models.deletion.CASCADE, related_name='tnris_training_ids', to='tnris_org.TnrisForumTraining'),
        ),
        migrations.AlterUniqueTogether(
            name='tnrisinstructorrelate',
            unique_together={('instructor_relate_id', 'training_relate_id')},
        ),
    ]
