# Generated by Django 2.0.13 on 2019-08-08 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0015_auto_20190808_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnrisInstructorType',
            fields=[
                ('instructor_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Instructor Type ID')),
                ('name', models.CharField(max_length=100, verbose_name='Instructor Name')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instructor Company')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Instructor Bio')),
                ('headshot', models.URLField(blank=True, max_length=255, null=True, verbose_name='Image URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Tnris Instructor Type',
                'verbose_name_plural': 'Tnris Instructor Types',
                'db_table': 'tnris_instructor_type',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='tnrisinstructorrelate',
            name='instructor_relate_id',
            field=models.ForeignKey(db_column='instructor_relate_id', on_delete=django.db.models.deletion.CASCADE, related_name='tnris_instructor_type_ids', to='tnris_org.TnrisInstructorType'),
        ),
        migrations.AlterField(
            model_name='tnrisinstructorrelate',
            name='training_relate_id',
            field=models.ForeignKey(db_column='training_relate_id', on_delete=django.db.models.deletion.CASCADE, related_name='tnris_forum_training_ids', to='tnris_org.TnrisForumTraining'),
        ),
        migrations.DeleteModel(
            name='TnrisInstructor',
        ),
    ]
