# Generated by Django 2.0.13 on 2019-08-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0016_auto_20190808_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteForumTrainingView',
            fields=[
                ('training_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Training ID')),
                ('training_day', models.PositiveSmallIntegerField(verbose_name='Forum Training Day')),
                ('title', models.CharField(max_length=255, verbose_name='Training Title')),
                ('start_date_time', models.DateTimeField(verbose_name='Training Start Date & Time')),
                ('end_date_time', models.DateTimeField(verbose_name='Training End Date & Time')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Training Cost')),
                ('registration_open', models.BooleanField(verbose_name='Registration Open')),
                ('public', models.BooleanField(verbose_name='Public')),
                ('location', models.CharField(max_length=255, verbose_name='Training Location')),
                ('room', models.CharField(max_length=255, verbose_name='Training Room')),
                ('max_students', models.PositiveSmallIntegerField(verbose_name='Max Student Amount')),
                ('description', models.TextField(verbose_name='Training Description')),
                ('teaser', models.TextField(verbose_name='Training Teaser')),
                ('instructor_info', models.TextField(verbose_name='Instructor Info')),
            ],
            options={
                'verbose_name': 'Complete Forum Training',
                'verbose_name_plural': 'Complete Forum Trainings',
                'db_table': 'complete_forum_training',
                'managed': False,
            },
        ),
    ]
