# Generated by Django 2.0.13 on 2019-08-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0018_tnrisgiocalendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrisgiocalendarevent',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode'),
        ),
    ]
