# Generated by Django 2.0.13 on 2019-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0019_auto_20190819_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrisgiocalendarevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event End Time'),
        ),
        migrations.AlterField(
            model_name='tnrisgiocalendarevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event Start Time'),
        ),
    ]
