# Generated by Django 2.0.13 on 2019-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0022_auto_20190821_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrisgiocalendarevent',
            name='community_meeting_agenda_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Community Meeting Agenda URL'),
        ),
    ]
