# Generated by Django 2.0.13 on 2020-05-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0024_tnrisdocument_sgm_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnristraining',
            name='training_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Training Course Registration Link'),
        ),
    ]
