# Generated by Django 2.0.13 on 2020-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0025_tnristraining_training_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnristraining',
            name='training_link',
            field=models.URLField(default='https://events.eply.com/TNRIS2020', max_length=255, verbose_name='Training Course Registration Link'),
            preserve_default=False,
        ),
    ]
