# Generated by Django 2.0.13 on 2020-05-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0027_trainingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnristraining',
            name='category',
            field=models.ForeignKey(db_column='training_category_id', default='b616cc6a-8edb-42b5-ba46-30053d9813e6', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='tnris_org.TrainingCategory'),
            preserve_default=False,
        ),
    ]
