# Generated by Django 2.0.13 on 2020-05-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0028_tnristraining_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnristraining',
            name='category',
            field=models.ForeignKey(db_column='training_category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='tnris_org.TrainingCategory'),
        ),
    ]
