# Generated by Django 2.0.13 on 2020-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0029_auto_20200518_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcategory',
            name='training_category',
            field=models.CharField(help_text='No "&" or "?" special characters allowed! These are reserved characters used by the API for querying.', max_length=100, verbose_name='Category'),
        ),
    ]
