# Generated by Django 2.0.13 on 2020-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0030_auto_20200520_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrisdocument',
            name='comm_note',
            field=models.BooleanField(default=False, verbose_name='GIS Community Meeting Note'),
        ),
    ]
