# Generated by Django 3.0.8 on 2020-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0031_tnrisdocument_comm_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrisdocument',
            name='document_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Document Name'),
        ),
    ]
