# Generated by Django 3.0.8 on 2021-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0033_auto_20201215_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrisimage',
            name='carousel',
            field=models.BooleanField(default=False, verbose_name='Carousel Image'),
        ),
    ]
