# Generated by Django 3.0.8 on 2021-04-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0034_tnrisimage_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrisimage',
            name='carousel_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Carousel Caption'),
        ),
    ]
