# Generated by Django 3.0.8 on 2021-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnris_org', '0035_tnrisimage_carousel_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrisimage',
            name='carousel_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Carousel Image Link'),
        ),
        migrations.AddField(
            model_name='tnrisimage',
            name='carousel_order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Carousel Image Order'),
        ),
    ]
