# Generated by Django 2.0.13 on 2019-04-30 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lcd', '0039_auto_20190403_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Map Collection ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('thumbnail_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Link')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Map Collection',
                'verbose_name_plural': 'Map Collections',
                'db_table': 'map_collection',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MapDataRelate',
            fields=[
                ('map_data_relate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Map Data Relate ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('data_collection_id', models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, related_name='data_collection', to='lcd.Collection')),
                ('map_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_collection', to='msd.MapCollection')),
            ],
            options={
                'verbose_name': 'Map Data Lookup',
                'verbose_name_plural': 'Map Data Lookups',
                'db_table': 'map_data_relate',
            },
        ),
        migrations.CreateModel(
            name='MapDownload',
            fields=[
                ('map_download_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Map Download ID')),
                ('download_url', models.URLField(max_length=255, verbose_name='Image URL')),
                ('label', models.CharField(max_length=100, verbose_name='Map Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('map_collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_collection_download', to='msd.MapCollection')),
            ],
            options={
                'verbose_name': 'Map Download',
                'verbose_name_plural': 'Map Downlaods',
                'db_table': 'map_download',
            },
        ),
        migrations.CreateModel(
            name='MapSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='35 Character Limit', max_length=35, unique=True, verbose_name='Label')),
                ('length', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, verbose_name='Width')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Map Size',
                'verbose_name_plural': 'Map Sizes',
                'db_table': 'map_size',
            },
        ),
        migrations.CreateModel(
            name='PixelsPerInch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pixels_per_inch', models.PositiveIntegerField(unique=True, verbose_name='PPI')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Pixels Per Inch',
                'verbose_name_plural': 'Pixels Per Inch',
                'db_table': 'pixels_per_inch',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mapsize',
            unique_together={('length', 'width')},
        ),
        migrations.AddField(
            model_name='mapdownload',
            name='map_size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_collection_download', to='msd.MapSize'),
        ),
        migrations.AddField(
            model_name='mapdownload',
            name='pixels_per_inch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_collection_download', to='msd.PixelsPerInch'),
        ),
        migrations.AlterUniqueTogether(
            name='mapdownload',
            unique_together={('map_collection_id', 'download_url')},
        ),
        migrations.AlterUniqueTogether(
            name='mapdatarelate',
            unique_together={('data_collection_id', 'map_collection_id')},
        ),
    ]
