# Generated by Django 2.0.13 on 2019-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelsperinch',
            name='pixels_per_inch',
            field=models.PositiveIntegerField(unique=True, verbose_name='Pixels Per Inch'),
        ),
    ]
