# Generated by Django 2.0.13 on 2019-04-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0002_auto_20190430_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdownload',
            options={'verbose_name': 'Map Download', 'verbose_name_plural': 'Map Downloads'},
        ),
    ]
