# Generated by Django 2.0.13 on 2019-04-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0003_auto_20190430_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdatarelate',
            name='map_collection_id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='map_collection', to='msd.MapCollection'),
        ),
    ]
