# Generated by Django 2.0.13 on 2019-04-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0004_auto_20190430_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapcollection',
            old_name='id',
            new_name='map_collection_id',
        ),
        migrations.RenameField(
            model_name='mapdownload',
            old_name='map_size_id',
            new_name='map_size',
        ),
        migrations.RenameField(
            model_name='mapdownload',
            old_name='pixels_per_inch_id',
            new_name='pixels_per_inch',
        ),
        migrations.AlterField(
            model_name='mapdatarelate',
            name='map_collection_id',
            field=models.ForeignKey(db_column='map_collection_id', on_delete=django.db.models.deletion.CASCADE, related_name='map_collection', to='msd.MapCollection'),
        ),
        migrations.AlterField(
            model_name='mapdownload',
            name='map_collection_id',
            field=models.ForeignKey(db_column='map_collection_id', on_delete=django.db.models.deletion.CASCADE, related_name='map_collection_download', to='msd.MapCollection'),
        ),
    ]
