# Generated by Django 2.0.13 on 2019-05-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0005_auto_20190430_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdownload',
            name='download_url',
            field=models.URLField(max_length=255, verbose_name='Download URL'),
        ),
    ]
