# Generated by Django 2.0.13 on 2019-05-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0006_auto_20190502_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdownload',
            name='download_url',
            field=models.URLField(blank=True, max_length=350, null=True, verbose_name='Download URL'),
        ),
    ]
