# Generated by Django 2.0.13 on 2019-05-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0007_auto_20190502_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdownload',
            name='download_url',
            field=models.URLField(max_length=350, verbose_name='Download URL'),
        ),
    ]
