# Generated by Django 2.0.13 on 2019-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0008_auto_20190502_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsdView',
            fields=[
                ('collection_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Map Collection ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail_link', models.CharField(max_length=255, verbose_name='Thumbnail Link')),
                ('public', models.BooleanField(verbose_name='Public')),
                ('data_collections', models.TextField(verbose_name='Data Collections')),
                ('map_downloads', models.TextField(verbose_name='Map Downloads')),
            ],
            options={
                'verbose_name': 'Master Systems Display',
                'verbose_name_plural': 'Master Systems Display',
                'db_table': 'master_systems_display',
                'managed': False,
            },
        ),
    ]
