# Generated by Django 2.0.13 on 2019-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msd', '0010_mapcollection_more_info_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcollection',
            name='more_info_url',
        ),
        migrations.AddField(
            model_name='mapcollection',
            name='more_info_link',
            field=models.URLField(blank=True, max_length=350, null=True, verbose_name='More Info Link'),
        ),
    ]
