# Generated by Django 4.2.9 on 2024-07-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog2021',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time without timezone')),
                ('x_edge_result_type', models.CharField(verbose_name='X Edge Result Type')),
                ('x_edge_detailed_result_type', models.TextField(verbose_name='X Edge Detailed Result Type')),
                ('x_host_header', models.CharField(verbose_name='X Host Header')),
                ('cs_uri_stem', models.TextField(verbose_name='CS URI Stem')),
                ('collection_id', models.CharField(verbose_name='Collection ID')),
                ('collection_shortname', models.CharField(verbose_name='Collection Short Name')),
                ('area_type_id', models.CharField(verbose_name='Area Type ID')),
                ('file_type', models.CharField(verbose_name='File Type')),
                ('hist_band', models.CharField(verbose_name='Hist Band')),
                ('hist_collective', models.CharField(verbose_name='Hist Collective')),
                ('hist_mission', models.CharField(verbose_name='Hist Mission')),
                ('hist_type', models.CharField(verbose_name='Hist Type')),
                ('hist_product', models.CharField(verbose_name='Hist Product')),
                ('hist_file', models.CharField(verbose_name='Hist File')),
            ],
            options={
                'verbose_name': 'Download log 2021 entry',
                'verbose_name_plural': 'Download logs 2021',
                'db_table': 'download_log_2021',
            },
        ),
        migrations.CreateModel(
            name='DownloadLog2022',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time without timezone')),
                ('x_edge_result_type', models.CharField(verbose_name='X Edge Result Type')),
                ('x_edge_detailed_result_type', models.TextField(verbose_name='X Edge Detailed Result Type')),
                ('x_host_header', models.CharField(verbose_name='X Host Header')),
                ('cs_uri_stem', models.TextField(verbose_name='CS URI Stem')),
                ('collection_id', models.CharField(verbose_name='Collection ID')),
                ('collection_shortname', models.CharField(verbose_name='Collection Short Name')),
                ('area_type_id', models.CharField(verbose_name='Area Type ID')),
                ('file_type', models.CharField(verbose_name='File Type')),
                ('hist_band', models.CharField(verbose_name='Hist Band')),
                ('hist_collective', models.CharField(verbose_name='Hist Collective')),
                ('hist_mission', models.CharField(verbose_name='Hist Mission')),
                ('hist_type', models.CharField(verbose_name='Hist Type')),
                ('hist_product', models.CharField(verbose_name='Hist Product')),
                ('hist_file', models.CharField(verbose_name='Hist File')),
            ],
            options={
                'verbose_name': 'Download log 2022 entry',
                'verbose_name_plural': 'Download logs 2022',
                'db_table': 'download_log_2022',
            },
        ),
        migrations.CreateModel(
            name='DownloadLog2023',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time without timezone')),
                ('x_edge_result_type', models.CharField(verbose_name='X Edge Result Type')),
                ('x_edge_detailed_result_type', models.TextField(verbose_name='X Edge Detailed Result Type')),
                ('x_host_header', models.CharField(verbose_name='X Host Header')),
                ('cs_uri_stem', models.TextField(verbose_name='CS URI Stem')),
                ('collection_id', models.CharField(verbose_name='Collection ID')),
                ('collection_shortname', models.CharField(verbose_name='Collection Short Name')),
                ('area_type_id', models.CharField(verbose_name='Area Type ID')),
                ('file_type', models.CharField(verbose_name='File Type')),
                ('hist_band', models.CharField(verbose_name='Hist Band')),
                ('hist_collective', models.CharField(verbose_name='Hist Collective')),
                ('hist_mission', models.CharField(verbose_name='Hist Mission')),
                ('hist_type', models.CharField(verbose_name='Hist Type')),
                ('hist_product', models.CharField(verbose_name='Hist Product')),
                ('hist_file', models.CharField(verbose_name='Hist File')),
            ],
            options={
                'verbose_name': 'Download log 2023 entry',
                'verbose_name_plural': 'Download logs 2023',
                'db_table': 'download_log_2023',
            },
        ),
        migrations.CreateModel(
            name='DownloadLog2024',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time without timezone')),
                ('x_edge_result_type', models.CharField(verbose_name='X Edge Result Type')),
                ('x_edge_detailed_result_type', models.TextField(verbose_name='X Edge Detailed Result Type')),
                ('x_host_header', models.CharField(verbose_name='X Host Header')),
                ('cs_uri_stem', models.TextField(verbose_name='CS URI Stem')),
                ('collection_id', models.CharField(verbose_name='Collection ID')),
                ('collection_shortname', models.CharField(verbose_name='Collection Short Name')),
                ('area_type_id', models.CharField(verbose_name='Area Type ID')),
                ('file_type', models.CharField(verbose_name='File Type')),
                ('hist_band', models.CharField(verbose_name='Hist Band')),
                ('hist_collective', models.CharField(verbose_name='Hist Collective')),
                ('hist_mission', models.CharField(verbose_name='Hist Mission')),
                ('hist_type', models.CharField(verbose_name='Hist Type')),
                ('hist_product', models.CharField(verbose_name='Hist Product')),
                ('hist_file', models.CharField(verbose_name='Hist File')),
            ],
            options={
                'verbose_name': 'Download log 2024 entry',
                'verbose_name_plural': 'Download logs 2024',
                'db_table': 'download_log_2024',
            },
        ),
    ]
