# Generated by Django 2.0.6 on 2018-10-31 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0003_auto_20180904_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedPhotoIndexLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='Designated Year')),
                ('size', models.CharField(max_length=20, verbose_name='Labeled Size')),
                ('link', models.URLField(verbose_name='Download Link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lore.Collection')),
            ],
            options={
                'verbose_name': 'Photo Index Scanned LS4 Link',
                'verbose_name_plural': 'Photo Index Scanned LS4 Links',
                'db_table': 'photo_index_scanned_ls4_link',
            },
        ),
        migrations.AlterUniqueTogether(
            name='scannedphotoindexlink',
            unique_together={('collection_id', 'link')},
        ),
    ]
