# Generated by Django 2.0.6 on 2018-10-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0004_auto_20181031_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scannedphotoindexlink',
            old_name='collection_id',
            new_name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='scannedphotoindexlink',
            unique_together={('collection', 'link')},
        ),
    ]
