# Generated by Django 2.0.6 on 2018-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0005_auto_20181031_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedphotoindexlink',
            name='sheet',
            field=models.CharField(default='test', max_length=20, verbose_name='Sheet Number'),
            preserve_default=False,
        ),
    ]
