# Generated by Django 2.0.8 on 2019-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0007_auto_20181113_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='general_scale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='media_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='sample_image_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Index Service URL'),
        ),
    ]
