# Generated by Django 2.0.8 on 2019-03-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0008_auto_20190305_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='sample_image_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Sample Image URL'),
        ),
    ]
