# Generated by Django 2.0.13 on 2019-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0009_auto_20190305_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='number_of_boxes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Boxes'),
        ),
        migrations.AddField(
            model_name='collection',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='QR Code URL'),
        ),
    ]
