# Generated by Django 2.0.13 on 2019-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0010_auto_20190514_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clean_status',
            field=models.BooleanField(default=True, verbose_name='Clean'),
        ),
    ]
