# Generated by Django 2.0.13 on 2019-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0011_product_clean_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clean_status',
            field=models.BooleanField(default=False, verbose_name='Clean Status'),
        ),
    ]
