# Generated by Django 2.0.13 on 2020-01-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0012_auto_20191218_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='fully_scanned',
            field=models.BooleanField(default=False, verbose_name='Fully Scanned'),
        ),
    ]
