# Generated by Django 2.0.13 on 2020-02-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0013_collection_fully_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='photo_index_only',
            field=models.BooleanField(default=False, verbose_name='Photo Index Only'),
        ),
    ]
