# Generated by Django 2.0.13 on 2020-02-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0014_collection_photo_index_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lore.Scale'),
        ),
        migrations.AlterUniqueTogether(
            name='photoindex',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='scanned',
        ),
    ]
