# Generated by Django 2.0.13 on 2020-02-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0015_auto_20200227_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoindex',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scale',
        ),
    ]
