# Generated by Django 2.0.13 on 2020-02-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0016_auto_20200227_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
