# Generated by Django 2.0.13 on 2020-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0018_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='collection',
            name='thumbnail_image',
            field=models.TextField(blank=True, default='https://s3.amazonaws.com/data.tnris.org/historical_images/historical_thumbnail.jpg', max_length=120, null=True, verbose_name='Thumb Image'),
        ),
    ]
