# Generated by Django 2.0.13 on 2020-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0019_auto_20200429_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='thumbnail_image',
            field=models.TextField(blank=True, default='https://s3.amazonaws.com/data.tnris.org/historical_images/historical_thumbnail.jpg', max_length=200, null=True, verbose_name='Thumb Image'),
        ),
    ]
