# Generated by Django 3.2.19 on 2023-11-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0022_auto_20200825_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='dl_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Download Link'),
        ),
    ]
