# Generated by Django 2.0.13 on 2019-09-24 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('email_template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Email Template ID')),
                ('email_template_type', models.CharField(max_length=50, verbose_name='Email Template Type')),
                ('email_template_subject', models.CharField(max_length=100, verbose_name='Email Template Subject')),
                ('email_template_body', models.TextField(verbose_name='Email Template Body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'contact_email_template',
            },
        ),
        migrations.CreateModel(
            name='GeneralContact',
            fields=[
                ('general_contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='General Contact ID')),
                ('question_or_comment', models.TextField(verbose_name='Question or Comment')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('organization', models.CharField(blank=True, max_length=20, null=True, verbose_name='Organization')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry')),
                ('industry_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry (Other)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'General Question or Comment',
                'verbose_name_plural': 'General Questions or Comments',
                'db_table': 'contact_general',
            },
        ),
    ]
