# Generated by Django 2.0.13 on 2019-09-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_emailtemplate_generalcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcontact',
            name='email_template',
        ),
    ]
