# Generated by Django 2.0.13 on 2019-09-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_generalcontact_email_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalcontact',
            old_name='question_or_comment',
            new_name='question_or_comments',
        ),
    ]
