# Generated by Django 2.0.13 on 2019-10-03 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20190924_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexasImageryServiceContact',
            fields=[
                ('texasimageryservice_contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Texas Imagery Service Contact ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('reason', models.CharField(max_length=80, verbose_name='Reason')),
                ('issue_screenshot', models.URLField(blank=True, max_length=255, null=True, verbose_name='Issue Screenshot URL')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('government_agency_or_affiliation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Government Agency or Affiliation')),
                ('question_or_comments', models.TextField(verbose_name='Question or Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Texas Imagery Service Question or Comment',
                'verbose_name_plural': 'Texas Imagery Service Questions or Comments',
                'db_table': 'contact_texasimageryservice',
            },
        ),
    ]
