# Generated by Django 2.0.13 on 2019-10-04 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_texasimageryservicecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexasImageryServiceRequest',
            fields=[
                ('texasimageryservice_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Texas Imagery Service Request ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('organization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organization')),
                ('contractor_access', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Are you requesting access on behalf of a contractor currently under contract with your agency?', max_length=3, null=True, verbose_name='Contractor Access')),
                ('relevant_project_of_partnership', models.CharField(blank=True, help_text='Name of project or relevant partnership for which imagery will be used:', max_length=150, null=True, verbose_name='Relevant Project of Partnership')),
                ('company_name', models.CharField(blank=True, help_text='Business name of contracting company performing the work:', max_length=150, null=True, verbose_name='Company Name')),
                ('name_of_qualifying_agency', models.CharField(blank=True, help_text='Name of the qualifying agency for which you are performing work under the project or formal partnership:', max_length=150, null=True, verbose_name='Name of Qualifying Agency')),
                ('email_of_qualifying_agency', models.CharField(blank=True, help_text='Contact email at qualifying agency with which you are formally partnering or performing contracted work:', max_length=150, null=True, verbose_name='Email of Qualifying Agency')),
                ('anticipated_project_end_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Anticipated Project End Date')),
                ('end_date', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('No', 'No'), ('Possible', 'Possible'), ('Likely', 'Likely')], default='N/A', help_text='Is the anticipated end date likely to be extended?', max_length=8, null=True, verbose_name='End Date likely to be extended?')),
                ('best_effort', models.BooleanField(default=False, help_text='Imagery web services are provided as a ‘best effort’ level service; there is no implied or explicit high availability service-level agreement for the imagery web services.', verbose_name='Best Effort')),
                ('no_distribution', models.BooleanField(default=False, help_text='The organization-specific web service URL or other credentials for accessing the imagery as a service may not to be distributed outside of your organization. Usage statistics will be kept to inform the acquisition of future imagery updates and to support sustained funding for the license.', verbose_name='No Distribution')),
                ('horizontal_accuracy', models.BooleanField(default=False, help_text='Stated horizontal positional accuracy of the imagery is expected to achieve or exceed one meter (CE90) in most areas without significant vertical relief. Higher precision is expected in urban areas, where existing supplemental ground control was more abundant.', verbose_name='Horizontal Accuracy')),
                ('datum_transformation', models.BooleanField(default=False, help_text='A datum transformation may be required to achieve the highest level of positional accuracy, especially when reprojecting imagery between NAD27, NAD83, and WGS84-based datums.', verbose_name='Datum Transformation')),
                ('contractors', models.BooleanField(default=False, help_text="Contractors or formal partners performing work on behalf of a licensee must apply separately for access to the imagery service if it is to be used outside the immediate licensee's physical facilities or network.", verbose_name='Contractors')),
                ('reselling', models.BooleanField(default=False, help_text='Imagery files may not be resold, leased, rented or redistributed outside of your immediate organization or used for projects not identified to and approved by TNRIS. Providing mass downloads of any imagery files or derivative works containing the imagery is not permitted.', verbose_name='reselling')),
                ('primary_contact_signature', models.CharField(blank=True, max_length=150, null=True, verbose_name='Primary Contact Signature')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Texas Imagery Service Request',
                'verbose_name_plural': 'Texas Imagery Service Requests',
                'db_table': 'contact_texasimageryservice_request',
            },
        ),
        migrations.AlterField(
            model_name='texasimageryservicecontact',
            name='reason',
            field=models.CharField(choices=[('Feedback/General Inquiry', 'Feedback/General Inquiry'), ('Issue Reporting', 'Issue Reporting')], default='Feedback/General Inquiry', help_text='Reason for contacting', max_length=80, verbose_name='Reason'),
        ),
    ]
