# Generated by Django 2.0.13 on 2019-10-07 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20191004_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterGallerySubmission',
            fields=[
                ('postergallery_submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Poster Gallery Submission ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('organization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organization')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Poster Gallery Submission',
                'verbose_name_plural': 'Poster Gallery Submissions',
                'db_table': 'contact_postergallery_submission',
            },
        ),
    ]
