# Generated by Django 2.0.13 on 2019-10-07 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_postergallerysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumJobBoardSubmission',
            fields=[
                ('forumjobboard_submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Forum Job Board Submission ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('organization', models.CharField(blank=True, max_length=20, null=True, verbose_name='Organization')),
                ('job_description_upload', models.URLField(blank=True, max_length=360, null=True, verbose_name='Job Description Upload URL')),
                ('other_notes', models.TextField(blank=True, null=True, verbose_name='Other Notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Forum Job Board Submission',
                'verbose_name_plural': 'Forum Job Board Submissions',
                'db_table': 'contact_forumjobboard_submission',
            },
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template_type',
            field=models.CharField(help_text='Layman text of Form Submission table name.', max_length=50, verbose_name='Email Template Type'),
        ),
    ]
