# Generated by Django 2.0.13 on 2019-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20191007_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template_type',
            field=models.CharField(help_text='Layman text/name of Form Submission table/model class.', max_length=50, verbose_name='Email Template Type'),
        ),
    ]
