# Generated by Django 2.0.13 on 2019-10-07 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20191007_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeorodeoCallForPresentationsSubmission',
            fields=[
                ('georodeocallforpresentations_submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Georodeo Call for Presentations Submission ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('organizationtitle', models.CharField(blank=True, help_text='Presenter organizaion name and position title', max_length=60, null=True, verbose_name='Organization & Title')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Presenter Bio')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('supplementallink', models.TextField(blank=True, null=True, verbose_name='Supplemental Link')),
                ('presenterheadshotphoto', models.URLField(blank=True, max_length=360, null=True, verbose_name='Presenter Headshot Photo URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Georodeo Call for Presentations Submission',
                'verbose_name_plural': 'Georodeo Call for Presentations Submissions',
                'db_table': 'contact_georodeocallforpresentations_submission',
            },
        ),
    ]
