# Generated by Django 2.0.13 on 2019-10-07 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_georodeocallforpresentationssubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeorodeoRegistration',
            fields=[
                ('georodeoregistration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Georodeo Registration ID')),
                ('firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('organization', models.CharField(blank=True, max_length=60, null=True, verbose_name='Organization')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Position Title')),
                ('vegetarian', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Would you like to reserve a vegetarian lunch?', max_length=3, null=True, verbose_name='Vegetarian')),
                ('attendingsocial', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Do you plan on attending the post-event social?', max_length=3, null=True, verbose_name='Attending Social')),
                ('tnrisemails', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Would you like to receive emails from TNRIS related to future events?', max_length=3, null=True, verbose_name='TNRIS Emails')),
                ('partneremails', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Would you like to receive emails from sponsors and partners?', max_length=3, null=True, verbose_name='Partner Emails')),
                ('previouslyattended', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Have you ever attended the GeoRodeo before?', max_length=3, null=True, verbose_name='Previously Attended')),
                ('experience', models.CharField(blank=True, default='N/A', help_text='Non-Existent, Beginner, Intermediate, Kind of a Big Deal..., Elite Level Hacker, etc.', max_length=60, null=True, verbose_name='Experience Level')),
                ('tools', models.TextField(blank=True, help_text='What coding languages, tools, and/or libraries do you use?', null=True, verbose_name='Tools')),
                ('expectations', models.TextField(blank=True, help_text='What do you expect to hear about or learn at the GeoRodeo?', null=True, verbose_name='Expectations')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Georodeo Registration',
                'verbose_name_plural': 'Georodeo Registrations',
                'db_table': 'contact_georodeoregistration',
            },
        ),
    ]
