# Generated by Django 2.0.13 on 2019-10-09 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_georodeoregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LakesOfTexasContact',
            fields=[
                ('lakesoftexas_contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Lakes of Texas Contact ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Question or Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Lakes of Texas Question or Comment',
                'verbose_name_plural': 'Lakes of Texas Questions or Comments',
                'db_table': 'contact_lakesoftexas',
            },
        ),
    ]
