# Generated by Django 2.0.13 on 2019-10-09 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_lakesoftexascontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHubContact',
            fields=[
                ('datahub_contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='General Contact ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collection Name')),
                ('uuid', models.UUIDField(blank=True, null=True, verbose_name='Collection UUID')),
                ('category', models.CharField(blank=True, max_length=350, null=True, verbose_name='Category')),
                ('software', models.CharField(blank=True, max_length=100, null=True, verbose_name='Software')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Question or Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'DataHub Question or Comment',
                'verbose_name_plural': 'DataHub Questions or Comments',
                'db_table': 'contact_datahub',
            },
        ),
    ]
