# Generated by Django 2.0.13 on 2019-10-10 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_datahubcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHubOrder',
            fields=[
                ('datahub_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DataHub Order ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('organization', models.CharField(blank=True, max_length=60, null=True, verbose_name='Organization')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry')),
                ('harddrive', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hard Drive')),
                ('delivery', models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery Method')),
                ('payment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('order', models.TextField(blank=True, null=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'DataHub Order',
                'verbose_name_plural': 'DataHub Orders',
                'db_table': 'contact_datahub_order',
            },
        ),
        migrations.AlterField(
            model_name='datahubcontact',
            name='datahub_contact_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DataHub Contact ID'),
        ),
    ]
