# Generated by Django 2.0.13 on 2019-10-10 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_auto_20191010_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHubOutsideEntityContact',
            fields=[
                ('datahub_outsideentity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DataHub Outside Entity Contact ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('category', models.CharField(blank=True, max_length=350, null=True, verbose_name='Category')),
                ('software', models.CharField(blank=True, max_length=100, null=True, verbose_name='Software')),
                ('send_to_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sent to Email')),
                ('send_to_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sent to Name')),
                ('tnris_link', models.URLField(blank=True, max_length=360, null=True, verbose_name='TNRIS Outside Entity Card URL')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Question or Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'DataHub Outside Entity Question or Comment',
                'verbose_name_plural': 'DataHub Outside Entity Questions or Comments',
                'db_table': 'contact_datahub_outsideentity',
            },
        ),
    ]
