# Generated by Django 2.0.13 on 2019-10-10 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_datahuboutsideentitycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMap',
            fields=[
                ('map_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Map Order ID')),
                ('map_option', models.CharField(blank=True, choices=[('USGS', 'USGS'), ('NWI', 'NWI'), ('FEMA', 'FEMA')], help_text='For Federal Prints only.', max_length=10, null=True, verbose_name='Map Option')),
                ('map_description', models.TextField(blank=True, help_text='List all quads/panels and specify quantity for each map. For Federal Prints only.', null=True, verbose_name='Map Description')),
                ('map_collection_name', models.CharField(blank=True, help_text='For Pre-made Maps only.', max_length=300, null=True, verbose_name='Map Collection Name')),
                ('map_sheet', models.CharField(blank=True, help_text='For Pre-made Maps only.', max_length=300, null=True, verbose_name='Map Sheet')),
                ('legislative_request', models.BooleanField(default=False, help_text='For Pre-made Maps only.', verbose_name='Legislative Request?')),
                ('map_size', models.CharField(blank=True, choices=[('8.5_by_11', '8.5_by_11'), ('11_by_17', '11_by_17'), ('24_by_24', '24_by_24'), ('24_by_28', '24_by_28'), ('30_by_30', '30_by_30'), ('36_by_36', '36_by_36'), ('60_by_60', '60_by_60'), ('custom_xlarge', 'custom_xlarge')], help_text='For Custom Maps only.', max_length=20, null=True, verbose_name='Map Size')),
                ('custom_map_size', models.CharField(blank=True, help_text='Custom sizes requests are only accepted for sizes greater than 60 x 60. For Custom Maps only.', max_length=100, null=True, verbose_name='Custom Map Size')),
                ('map_scale', models.CharField(blank=True, help_text='For Custom Maps only.', max_length=100, null=True, verbose_name='Map Scale')),
                ('map_title', models.CharField(blank=True, help_text='For Custom Maps only.', max_length=200, null=True, verbose_name='Map Title')),
                ('map_date', models.CharField(blank=True, help_text='For Custom Maps only.', max_length=100, null=True, verbose_name='Map Date')),
                ('type_of_data', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Maps', 'Maps')], default='Maps', max_length=25, null=True, verbose_name='Type of Data')),
                ('type_of_map', models.CharField(blank=True, choices=[('Federal Print', 'Federal Print'), ('Pre-Made Print', 'Pre-Made Print'), ('Custom', 'Custom')], max_length=20, null=True, verbose_name='Type of Map')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Info')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry')),
                ('industry_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry (Other)')),
                ('address_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=75, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Zip')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('delivery_method', models.CharField(blank=True, choices=[('Digital Download', 'Digital Download'), ('USPS', 'USPS'), ('FedEx', 'FedEx'), ('FedEx Customer Charged', 'FedEx Customer Charged')], max_length=30, null=True, verbose_name='Delivery Method')),
                ('fedex_customer_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='FedEx Customer Number')),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Check', 'Check'), ('Pay at Pickup', 'Pay at Pickup'), ('Purchase Order', 'Purchase Order')], max_length=30, null=True, verbose_name='Payment Method')),
                ('check_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Check Number')),
                ('purchase_order_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Purchase Order Number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Map Order',
                'verbose_name_plural': 'Map Orders',
                'db_table': 'contact_ordermap',
            },
        ),
        migrations.AlterField(
            model_name='generalcontact',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization'),
        ),
    ]
