# Generated by Django 2.0.13 on 2019-10-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_auto_20191010_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='texasimageryservicerequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='texasimageryservicerequest',
            name='credentialed_url',
            field=models.URLField(blank=True, null=True, verbose_name='Credentialed URL'),
        ),
        migrations.AddField(
            model_name='texasimageryservicerequest',
            name='non_credentialed_wms_link',
            field=models.URLField(blank=True, null=True, verbose_name='Non-Credentialed WMS Link'),
        ),
        migrations.AddField(
            model_name='texasimageryservicerequest',
            name='non_credentialed_wmts_link',
            field=models.URLField(blank=True, null=True, verbose_name='Non-Credentialed WMTS Link'),
        ),
        migrations.AddField(
            model_name='texasimageryservicerequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='texasimageryservicerequest',
            name='password',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='texasimageryservicerequest',
            name='username',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Username'),
        ),
    ]
