# Generated by Django 2.0.13 on 2019-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_auto_20191011_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texasimageryservicerequest',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization'),
        ),
    ]
