# Generated by Django 2.0.13 on 2019-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_texasimageryservicerequest_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texasimageryservicerequest',
            name='contractor_access',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Are you requesting access on behalf of a contractor currently under contract with your agency?', max_length=3, verbose_name='Contractor Access'),
        ),
        migrations.AlterField(
            model_name='texasimageryservicerequest',
            name='end_date',
            field=models.CharField(choices=[('N/A', 'N/A'), ('No', 'No'), ('Possible', 'Possible'), ('Likely', 'Likely')], default='N/A', help_text='Is the anticipated end date likely to be extended?', max_length=8, verbose_name='End Date likely to be extended?'),
        ),
    ]
