# Generated by Django 2.0.13 on 2019-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_auto_20191011_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texasimageryservicerequest',
            name='contractor_access',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], default='N/A', help_text='Are you requesting access on behalf of a contractor currently under contract with your agency?', max_length=3, verbose_name='Contractor Access'),
        ),
        migrations.AlterField(
            model_name='texasimageryservicerequest',
            name='relevant_project_of_partnership',
            field=models.CharField(blank=True, help_text='Name of project or relevant partnership for which imagery will be used:', max_length=250, null=True, verbose_name='Relevant Project of Partnership'),
        ),
    ]
