# Generated by Django 2.0.13 on 2019-10-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_auto_20191011_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texasimageryservicerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Phone'),
        ),
    ]
