# Generated by Django 2.0.13 on 2019-10-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0023_auto_20191011_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='form_id',
            field=models.CharField(default='contact', help_text="'forum_id' value from form submission object.", max_length=40, verbose_name='Form ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sendpoint',
            field=models.CharField(choices=[('default', 'default'), ('email', 'email'), ('send_to_email', 'send_to_email')], default='default', help_text="'default' to send to ticketing system. otherwise, form object key with email address to send to.", max_length=20, verbose_name='Sendpoint'),
        ),
    ]
