# Generated by Django 2.0.13 on 2019-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0024_auto_20191011_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='form_id',
            field=models.CharField(help_text="'forum_id' value from form submission object.", max_length=40, unique=True, verbose_name='Form ID'),
        ),
    ]
