# Generated by Django 2.0.13 on 2019-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0028_auto_20191011_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template_body',
            field=models.TextField(default='A form has been submitted from: {{url}}\nForm ID: {{form_id}}\n\nForm parameters\n==================\n', verbose_name='Email Template Body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='serializer_classname',
            field=models.CharField(help_text="Serializer classname from serializers.py file. Must be exact. Typically is: '{{ModelClassname}}Serializer'", max_length=70, unique=True, verbose_name='Serializer Classname'),
        ),
    ]
