# Generated by Django 2.0.13 on 2019-10-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_auto_20191014_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template_body',
            field=models.TextField(default='A form has been submitted from: {{url}}\nForm ID: {{form_id}}\n\nForm parameters\n==================\n', help_text='Form field values can be used by surrounding the database field name with double curly brackets. Ex: {{field_name}}', verbose_name='Email Template Body'),
        ),
    ]
