# Generated by Django 2.0.13 on 2019-10-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0031_auto_20191016_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahubcontact',
            name='acquisition_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Acquisition Date'),
        ),
    ]
