# Generated by Django 2.0.13 on 2019-10-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0032_datahubcontact_acquisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georodeoregistration',
            name='experience',
            field=models.CharField(blank=True, help_text='Non-Existent, Beginner, Intermediate, Kind of a Big Deal..., Elite Level Hacker, etc.', max_length=60, null=True, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='georodeoregistration',
            name='previouslyattended',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Have you ever attended the GeoRodeo before?', max_length=3, null=True, verbose_name='Previously Attended'),
        ),
    ]
