# Generated by Django 2.0.13 on 2019-11-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_auto_20191018_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texasimageryservicerequest',
            name='comment',
        ),
    ]
