# Generated by Django 2.0.13 on 2020-04-03 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_remove_texasimageryservicerequest_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationContact',
            fields=[
                ('education_contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Education Contact ID')),
                ('question_or_comments', models.TextField(verbose_name='Question or Comment')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry')),
                ('industry_other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry (Other)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Education Question or Comment',
                'verbose_name_plural': 'Education Questions or Comments',
                'db_table': 'contact_education',
            },
        ),
    ]
