# Generated by Django 3.0.8 on 2020-10-06 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0035_educationcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('survey_template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Survey Template ID')),
                ('display_delay_template_type', models.PositiveSmallIntegerField(default=5, help_text='Integer value in seconds before modal appears.', verbose_name='Display Delay Template Type')),
                ('initial_content_state', models.CharField(choices=[('preview', 'preview'), ('full', 'full'), ('minimized', 'minimized'), ('none', 'none')], default='preview', help_text='Sets the initial content of the modal upon loading. Preview content is the default initial content state.', max_length=16, verbose_name='Initial Modal Content State')),
                ('preview_header', models.CharField(blank=True, help_text='The header for the Preview Content of the modal', max_length=40, null=True, verbose_name='Preview Modal Header')),
                ('preview_body_text', models.CharField(blank=True, help_text='The text content for the Preview Content of the modal', max_length=400, null=True, verbose_name='Preview Modal Body Text')),
                ('preview_accept_button_text', models.CharField(default='Accept', help_text='The text label for the preview accept button', max_length=20, verbose_name='Preview Modal Accept Button Text')),
                ('preview_reject_button_text', models.CharField(default='Reject', help_text='The text label for the preview reject button', max_length=20, verbose_name='Preview Modal Reject Button Text')),
                ('preview_later_button_text', models.CharField(default='Maybe Later', help_text='The text label for the preview later button', max_length=20, verbose_name='Preview Modal Later Button Text')),
                ('preview_position', models.CharField(choices=[('top-right', 'top-right'), ('top-left', 'top-left'), ('top-center', 'top-center'), ('bottom-right', 'bottom-right'), ('bottom-left', 'bottom-left'), ('bottom-center', 'bottom-center'), ('left-center', 'left-center'), ('right-center', 'right-center'), ('center', 'center')], default='bottom-right', help_text='Sets the position of the preview modal on the screen when loaded.', max_length=16, verbose_name='Preview Modal Position')),
                ('preview_size', models.CharField(choices=[('full-screen', 'full-screen'), ('full-height', 'full-height'), ('full-width', 'full-width'), ('half-width', 'half-width'), ('half-height', 'half-height')], default='half-width', help_text='Sets the size of the preview modal on the screen when loaded.', max_length=14, verbose_name='Preview Modal Size')),
                ('preview_background_color', models.CharField(blank=True, default='', help_text='Sets the background overlay color of the preview modal on load.', max_length=32, null=True, verbose_name='Preview Modal Background Overlay Color')),
                ('full_header', models.CharField(blank=True, help_text='The header for the Full Content of the modal', max_length=40, null=True, verbose_name='Full Modal Header')),
                ('full_body_text', models.CharField(blank=True, help_text='The text content for the Full Content of the modal', max_length=400, null=True, verbose_name='Full Body Text')),
                ('full_position', models.CharField(choices=[('top-right', 'top-right'), ('top-left', 'top-left'), ('top-center', 'top-center'), ('bottom-right', 'bottom-right'), ('bottom-left', 'bottom-left'), ('bottom-center', 'bottom-center'), ('left-center', 'left-center'), ('right-center', 'right-center'), ('center', 'center')], default='bottom-right', help_text='Sets the position of the preview modal on the screen when loaded.', max_length=16, verbose_name='Full Modal Position')),
                ('full_size', models.CharField(choices=[('full-screen', 'full-screen'), ('full-height', 'full-height'), ('full-width', 'full-width'), ('half-width', 'half-width'), ('half-height', 'half-height')], default='half-width', help_text='Sets the size of the full modal on the screen when loaded.', max_length=14, verbose_name='Full Modal Size')),
                ('full_background_color', models.CharField(blank=True, default='', help_text='Sets the background overlay color of the full modal on load.', max_length=32, null=True, verbose_name='Full Modal Background Overlay Color')),
                ('minimized_icon', models.CharField(default='minimize', help_text='Sets the icon for the minimized state of the modal', max_length=40, verbose_name='MDC Icon Text String')),
                ('minimized_text', models.CharField(default='minimize', help_text='Sets the label text for the minimized state of the modal', max_length=40, verbose_name='Minimized modal label text')),
                ('sheet_id', models.CharField(blank=True, help_text='Sets the Google Sheet id for survey results to be posted to', max_length=50, null=True, verbose_name='Google Sheet Id to post responses to')),
                ('survey_id', models.CharField(blank=True, help_text='Sets the SurveyJS id for survey results to be posted to', max_length=50, null=True, verbose_name='SurveyJS Id to pull survey from')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Survey Template',
                'verbose_name_plural': 'Survey Templates',
                'db_table': 'survey_template',
            },
        ),
    ]
