# Generated by Django 3.0.8 on 2020-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0036_surveytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='survey_template_title',
            field=models.CharField(default='', help_text='An arbitrary title or descriptor for the survey modal', max_length=40, verbose_name='Survey Name'),
            preserve_default=False,
        ),
    ]
