# Generated by Django 3.0.8 on 2020-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0037_auto_20201006_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytemplate',
            name='full_background_color',
            field=models.CharField(blank=True, default='#333333c4', help_text='Sets the background overlay color of the full modal on load.', max_length=32, null=True, verbose_name='Full Modal Background Overlay Color'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='full_size',
            field=models.CharField(choices=[('full-screen', 'full-screen'), ('full-height', 'full-height'), ('full-width', 'full-width'), ('half-width', 'half-width'), ('half-height', 'half-height'), ('half-screen', 'half-screen'), ('fit-content', 'fit-content')], default='full-screen', help_text='Sets the size of the full modal on the screen when loaded.', max_length=14, verbose_name='Full Modal Size'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='minimized_icon',
            field=models.CharField(default='fact_check', help_text='Sets the icon for the minimized state of the modal', max_length=40, verbose_name='MDC Icon Text String'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='minimized_text',
            field=models.CharField(default='Take Survey', help_text='Sets the label text for the minimized state of the modal', max_length=40, verbose_name='Minimized modal label text'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='preview_reject_button_text',
            field=models.CharField(default='No Thanks', help_text='The text label for the preview reject button', max_length=20, verbose_name='Preview Modal Reject Button Text'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='preview_size',
            field=models.CharField(choices=[('full-screen', 'full-screen'), ('full-height', 'full-height'), ('full-width', 'full-width'), ('half-width', 'half-width'), ('half-height', 'half-height'), ('fit-content', 'fit-content')], default='fit-content', help_text='Sets the size of the preview modal on the screen when loaded.', max_length=14, verbose_name='Preview Modal Size'),
        ),
    ]
