# Generated by Django 3.0.8 on 2020-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0039_auto_20201119_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytemplate',
            name='content_type',
            field=models.CharField(choices=[('single-modal', 'single-modal'), ('multi-modal', 'multi-modal')], default='multi-modal', help_text='The display type of the modal; for example, should it display a series of dialogues, or should the modal be a single, static-text alert type.', max_length=16, verbose_name='Display Type'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='dev_mode',
            field=models.BooleanField(default=False, help_text='If checked, the modal will only display in development on localhost:3000', verbose_name='Dev Mode'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='full_body_text',
            field=models.TextField(blank=True, help_text='The text content for the Full Content of the modal', null=True, verbose_name='Full Body Text'),
        ),
    ]
