# Generated by Django 3.2.5 on 2022-02-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0041_campaign_campaignsubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['campaign_name'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='campaignsubscriber',
            options={'ordering': ['campaign__campaign_name'], 'verbose_name': 'Campaign Subscriber', 'verbose_name_plural': 'Campaign Subscribers'},
        ),
        migrations.AlterModelTable(
            name='campaignsubscriber',
            table='contact_campaign_subscriber',
        ),
    ]
