# Generated by Django 3.2.5 on 2022-02-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0042_auto_20220225_0843'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaign',
            table='contact_campaign',
        ),
    ]
