# Generated by Django 3.2.5 on 2022-02-25 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0043_alter_campaign_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='subscription identification number'),
        ),
        migrations.AlterField(
            model_name='campaignsubscriber',
            name='email',
            field=models.CharField(editable=False, max_length=140, unique=True, verbose_name='email'),
        ),
    ]
