# Generated by Django 3.2.5 on 2022-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0044_auto_20220225_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsubscriber',
            name='email',
            field=models.CharField(max_length=140, unique=True, verbose_name='email'),
        ),
    ]
