# Generated by Django 3.2.14 on 2023-01-05 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0045_alter_campaignsubscriber_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Auto increment primary key.')),
                ('unique_trans_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Transaction Id')),
                ('order_details', models.BinaryField(verbose_name='A Json containing order details. Encrypted values')),
                ('order_approved', models.BooleanField(default=False, verbose_name='Whether order has been approved')),
                ('access_code', models.CharField(max_length=1024, verbose_name='Order Private Access code')),
                ('access_salt', models.CharField(max_length=32, verbose_name='Salt for the access code')),
            ],
            options={
                'verbose_name': 'Order Type',
                'verbose_name_plural': 'Order Types',
                'db_table': 'order_type',
            },
        ),
    ]
