# Generated by Django 3.2.14 on 2023-02-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0046_cryptotext_orderdetailstype_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertype',
            name='order_sent',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Order Sent?'),
        ),
        migrations.AddField(
            model_name='ordertype',
            name='tnris_notified',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='TNRIS Notified?'),
        ),
    ]
