# Generated by Django 3.2.14 on 2023-02-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0047_auto_20230206_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertype',
            name='customer_notified',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Customer Notified?'),
        ),
    ]
