# Generated by Django 3.2.14 on 2023-02-15 15:57

import contact.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0048_ordertype_customer_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': 'DataHub New Order', 'verbose_name_plural': 'DataHub New Orders'},
        ),
        migrations.AddField(
            model_name='orderdetailstype',
            name='access_code',
            field=models.CharField(default=None, editable=False, max_length=255, null=True, verbose_name='Hash of access code.'),
        ),
        migrations.AddField(
            model_name='orderdetailstype',
            name='access_salt',
            field=models.CharField(default=None, editable=False, max_length=255, null=True, verbose_name='Salt for access code.'),
        ),
        migrations.AddField(
            model_name='orderdetailstype',
            name='otp',
            field=models.CharField(default=None, editable=False, max_length=255, null=True, verbose_name='One time passcode.'),
        ),
        migrations.AddField(
            model_name='orderdetailstype',
            name='otp_age',
            field=models.FloatField(default=None, editable=False, null=True, verbose_name='Age in seconds of the one time passcode.'),
        ),
        migrations.AlterField(
            model_name='orderdetailstype',
            name='details',
            field=contact.fields.CryptoTextField(max_length=50000, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='approved_charge',
            field=models.FloatField(blank=True, null=True, verbose_name='Approved Charge'),
        ),
    ]
