# Generated by Django 3.2.14 on 2023-03-01 23:56

import contact.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0049_auto_20230215_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailstype',
            name='details',
            field=contact.fields.CryptoTextField(editable=False, max_length=50000, verbose_name='Details'),
        ),
    ]
