# Generated by Django 3.2.14 on 2023-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0050_alter_orderdetailstype_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': 'DataHub New Order'},
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='order_sent',
            field=models.BooleanField(default=False, verbose_name='Order Sent?'),
        ),
    ]
