# Generated by Django 3.2.14 on 2023-04-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0050_alter_orderdetailstype_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='order_sent',
            field=models.BooleanField(default=False, verbose_name='Order Sent?'),
        ),
        migrations.AddConstraint(
            model_name='ordertype',
            constraint=models.CheckConstraint(check=models.Q(('order_approved', False), models.Q(('approved_charge__gte', 0.01), ('order_approved', True)), _connector='OR'), name='contact_ordertype_order_approved_constraint'),
        ),
    ]
