# Generated by Django 3.2.19 on 2024-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0051_auto_20230424_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailstype',
            name='email',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Temporarily store email'),
        ),
    ]
