# Generated by Django 3.2.19 on 2024-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0052_orderdetailstype_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailstype',
            name='email',
        ),
        migrations.AddField(
            model_name='orderdetailstype',
            name='update_email',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Update Email'),
        ),
    ]
