# Generated by Django 3.2.19 on 2024-05-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0053_auto_20240515_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='customer_notified',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Customer Notified?'),
        ),
    ]
