# Generated by Django 4.2.15 on 2025-04-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0054_alter_ordertype_customer_notified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderMap',
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': 'TxGIO Order', 'verbose_name_plural': 'TxGIO Orders'},
        ),
    ]
