# Generated by Django 4.2.15 on 2025-01-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0054_alter_ordertype_customer_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='order_token',
            field=models.CharField(default=None, editable=False, max_length=255, null=True, verbose_name='Order Token'),
        ),
    ]
