# Generated by Django 4.2.15 on 2025-01-13 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0054_alter_ordertype_customer_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReceived',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DataHub Order ID')),
            ],
            options={
                'verbose_name': 'Order Received',
                'verbose_name_plural': 'Orders Received',
            },
        ),
        migrations.CreateModel(
            name='OrderRemoved',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DataHub Order ID')),
            ],
            options={
                'verbose_name': 'Order Removed',
                'verbose_name_plural': 'Orders Removed',
            },
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='order_token',
            field=models.CharField(default=None, editable=False, max_length=255, null=True, verbose_name='Order Token'),
        ),
    ]
