# Generated by Django 4.2.15 on 2025-01-14 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0055_orderreceived_orderremoved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApproved',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DataHub Order ID')),
            ],
            options={
                'verbose_name': 'Order Approved',
                'verbose_name_plural': 'Orders Approved',
            },
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='serializer_classname',
            field=models.CharField(help_text="Serializer classname from serializers.py file. Must be exact. Typically is: '<-ModelClassname->Serializer'", max_length=70, verbose_name='Serializer Classname'),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name=''),
        ),
    ]
