# Generated by Django 4.2.15 on 2025-08-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0055_alter_emailtemplate_serializer_classname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataHubOrder',
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': 'DataHub Order', 'verbose_name_plural': 'DataHub Orders'},
        ),
    ]
