# Generated by Django 4.2.15 on 2025-01-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0056_orderapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='serializer_classname',
            field=models.CharField(help_text="Serializer classname from serializers.py file. Must be exact. Typically is: '<-ModelClassname->Serializer'", max_length=70, unique=True, verbose_name='Serializer Classname'),
        ),
    ]
