# Generated by Django 4.2.15 on 2025-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0057_alter_emailtemplate_serializer_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template_type',
            field=models.CharField(help_text='Layman text/name of Form Submission table/model class.', max_length=50, null=True, verbose_name='Email Template Type'),
        ),
    ]
