# Generated by Django 4.2.15 on 2025-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0060_alter_emailtemplate_serializer_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='serializer_classname',
            field=models.CharField(blank=True, help_text="Serializer classname from serializers.py file. Must be exact. Typically is: '<-ModelClassname->Serializer'", max_length=70, null=True, verbose_name='Serializer Classname'),
        ),
    ]
