export const SET_VIEW_CATALOG = 'SET_VIEW_CATALOG';
export const SET_VIEW_COLLECTION = 'SET_VIEW_COLLECTION';
export const SET_VIEW_ORDER_CART = 'SET_VIEW_ORDER_CART';
export const SET_VIEW_GEO_FILTER = 'SET_VIEW_GEO_FILTER';
export const SET_VIEW_NOT_FOUND = 'SET_VIEW_NOT_FOUND';

export const POP_BROWSER_STORE = 'POP_BROWSER_STORE';
