export const SET_COLLECTION_FILTER_MAP_AOI = 'SET_COLLECTION_FILTER_MAP_AOI';
export const SET_COLLECTION_FILTER_MAP_CENTER = 'SET_COLLECTION_FILTER_MAP_CENTER';
export const SET_COLLECTION_FILTER_MAP_FILTER = 'SET_COLLECTION_FILTER_MAP_FILTER';
export const SET_COLLECTION_FILTER_MAP_ZOOM = 'SET_COLLECTION_FILTER_MAP_ZOOM';
