export const FETCH_COLLECTIONS_BEGIN   = 'FETCH_COLLECTIONS_BEGIN';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_WITH_SELECTED_SUCCESS = 'FETCH_COLLECTIONS_WITH_SELECTED_SUCCESS';

export const SELECT_COLLECTION = 'SELECT_COLLECTION';
export const CLEAR_SELECTED_COLLECTION = 'CLEAR_SELECTED_COLLECTION';

export const FETCH_COLLECTION_RESOURCES_BEGIN   = 'FETCH_COLLECTION_RESOURCES_BEGIN';
export const FETCH_COLLECTION_RESOURCES_FAILURE = 'FETCH_PRODUCT_RESOURCES_FAILURE';
export const FETCH_COLLECTION_RESOURCES_SUCCESS = 'FETCH_COLLECTION_RESOURCES_SUCCESS';
