export const CLEAR_SELECTED_COLLECTION = 'CLEAR_SELECTED_COLLECTION';
export const FETCH_COLLECTIONS_BEGIN   = 'FETCH_COLLECTIONS_BEGIN';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const SELECT_COLLECTION = 'SELECT_COLLECTION';
