export const ADD_COLLECTION_TO_CART = 'ADD_COLLECTION_TO_CART';
export const REMOVE_COLLECTION_FROM_CART = 'REMOVE_COLLECTION_FROM_CART';

export const UPLOAD_ORDER_BEGIN = 'UPLOAD_ORDER_BEGIN';
export const UPLOAD_ORDER_SUCCESS = 'UPLOAD_ORDER_SUCCESS';
export const UPLOAD_ORDER_FAILURE = 'UPLOAD_ORDER_FAILURE';

export const SUBMIT_ORDER_BEGIN = 'SUBMIT_ORDER_BEGIN';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILURE = 'SUBMIT_ORDER_FAILURE';
