export const OPEN_TOOL_DRAWER = 'OPEN_TOOL_DRAWER';
export const CLOSE_TOOL_DRAWER = 'CLOSE_TOOL_DRAWER';
export const SET_DISMISSIBLE_DRAWER = 'SET_DISMISSIBLE_DRAWER';
export const SET_MODAL_DRAWER = 'SET_MODAL_DRAWER';
